# Portables Configuration
#
# Material List
# https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
#
# Enchantment List
# https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/enchantments/Enchantment.html
#
# Chest Lock Plugin
# Values: None, Deadbolt, LWC, Lockette, LockettePro
lockPlugin: none
#
# Player has to be within X blocks from host block. -1 to disable.
range: 350
#
# Portable items can only be linked to blocks in that world?
forceSameWorld: false
#
# Should the list below be worlds to disallow portable items in?
useWorldBlackList: true
# Worlds to allow usage of portable items
useInWorlds:
- Creative
#- world
#- world_nether
#- world_the_end
#
# Should the list below be worlds to disallow host block access?
hostWorldBlackList: true
# Worlds that the host block have to be in
hostWorlds:
- Creative
#- world
#- world_nether
#- world_the_end
#
# Portable Items
portables:
#  # Config Explination
#  # Material of item being used. (Item in hand)
#  ITEM_MATERIAL:
#    # Open on left click with item
#    PowerTool: true
#    # Open when right click item in inventory
#    InvShortcut: true
#    # Link by left clicking with item
#    Link: true
#    # Can portable item be crafted?
#    Craftable: true
#    # Is this portable only usable in its crafted form?
#    CraftOnly: true
#    # Crafting recipe. Use definitions below
#    Recipe: XYX,YAY,XYX
#    # Item name when crafted. Not linked yet (if applicable)
#    CraftedName: '&4Unlinked Portable Item'
#    # Item name when linked
#    LinkedName: '&aPortable Portable Item'
#    # Item lore when crafted. Not linked yet (if applicable)
#    Lore: 'Left click a placed{N}Host Block to link.'
#    # Enchantments applied when crafted. Will also apper when linked
#    Enchantments: DURABILITY:1
#    # Alternate blocks to link this item to. (Not every item enum matches its block version)
#    AltBlocks:
#    - BLOCK_MATERIAL
  # Brewing Stand
  BREWING_STAND_ITEM:
    PowerTool: true
    InvShortcut: true
    Link: true
    Craftable: true
    CraftOnly: true
    Recipe: XYX,YBY,XYX
    CraftedName: '&4Unlinked Brewing Stand'
    LinkedName: '&aPortable Brewing Stand'
    Lore: 'Left click a placed{N}Brewing Stand to link.'
    Enchantments: DURABILITY:1
    AltBlocks:
    - BREWING_STAND
  # Chest
  CHEST:
    PowerTool: true
    InvShortcut: true
    Link: true
    Craftable: true
    CraftOnly: true
    Recipe: XYX,YCY,XYX
    CraftedName: '&4Unlinked Chest'
    LinkedName: '&aPortable Chest'
    Lore: 'Left click a placed{N}Chest to link.'
    Enchantments: DURABILITY:1
    AltBlocks:
    - TRAPPED_CHEST
  # Dispenser
  DISPENSER:
    PowerTool: true
    InvShortcut: true
    Link: true
    Craftable: true
    CraftOnly: true
    Recipe: XYX,YDY,XYX
    CraftedName: '&4Unlinked Dispenser'
    LinkedName: '&aPortable Dispenser'
    Lore: 'Left click a placed{N}Dispenser to link.'
    Enchantments: DURABILITY:1
  # Dropper
  DROPPER:
    PowerTool: false
    InvShortcut: false
    Link: false
    Craftable: false
    CraftOnly: true
    Recipe: XYX,YJY,XYX
    CraftedName: '&4Unlinked Dropper'
    LinkedName: '&aPortable Dropper'
    Lore: 'Left click a placed{N}Dropper to link.'
    Enchantments: DURABILITY:1
  # Enchantment Table
  ENCHANTMENT_TABLE:
    PowerTool: true
    InvShortcut: true
    Link: true
    Craftable: true
    CraftOnly: true
    Recipe: XYX,YGY,XYX
    CraftedName: '&4Unlinked Enchantment Table'
    LinkedName: '&aPortable Enchantment Table'
    Lore: 'Left click a placed{N}Enchantment Table to link.'
    Enchantments: DURABILITY:1
  # EnderChest
  ENDER_CHEST:
    PowerTool: true
    InvShortcut: true
    Craftable: true
    CraftOnly: true
    Recipe: XYX,YEY,XYX
    CraftedName: '&6Portable Ender Chest'
    Lore: 'Right click with{N}inventory open to{N}open Ender Chest.'
    Enchantments: DURABILITY:1
  # Furnace
  FURNACE:
    PowerTool: true
    InvShortcut: true
    Link: true
    Craftable: true
    CraftOnly: true
    Recipe: XYX,YFY,XYX
    CraftedName: '&4Unlinked Furnace'
    LinkedName: '&aPortable Furnace'
    Lore: 'Left click a placed{N}Furnace to link.'
    Enchantments: DURABILITY:1
  # Hopper
  HOPPER:
    PowerTool: true
    InvShortcut: true
    Link: true
    Craftable: true
    CraftOnly: true
    Recipe: XYX,YHY,XYX
    CraftedName: '&4Unlinked Hopper'
    LinkedName: '&aPortable Hopper'
    Lore: 'Left click a placed{N}Hopper to link.'
    Enchantments: DURABILITY:1
  # Workbench (Crafting Table)
  WORKBENCH:
    PowerTool: true
    InvShortcut: true
    Craftable: true
    CraftOnly: false
    Recipe: XYX,YIY,XYX
    CraftedName: '&6Portable Crafting Table'
    Lore: 'Right click with{N}inventory open to{N}start crafting.'
    Enchantments: DURABILITY:1
#
# Items used in crafting
recipeDefinitions:
  B: BREWING_STAND_ITEM
  C: CHEST
  D: DISPENSER
  E: ENDER_CHEST
  F: FURNACE
  G: ENCHANTMENT_TABLE
  H: HOPPER
  I: WORKBENCH
  J: DROPPER
  X: REDSTONE_BLOCK
  Y: LEATHER
#
#
# Phrases
#
# No access to chest message
blockLocked: '&cYou are not authorized to access this {block}.'
# The host block is missing message
blockMissing: '&4Host {block} is missing or destroyed.'
# This is not a Portable item
invalidItem: 'This is not portable {block}.'
# This item is already linked
alreadyLinked: 'This {block} has already been linked.'
# Too far from block
outOfRange: 'You need to be within {range} blocks from host block.'
# World disabled message
worldNotAllowed: 'You are not alowed to use Portable items in this world.'
hostWorldNotAllowed: 'You are not allowed to remotly access blocks in this world.'
worldNotSame: 'You must use this item in the same world as it''s hosted.'
# Location in lore is invalid
invalidLocation: 'Invalid host location.'
# No permission messages
noPermLink: '&cYou do not have permission to link {block}.'
noPermUse: '&cYou do not have permission use portable {block}.'
# Command messages
noItemInHand: 'You must have a Portables item in your hand.'
notLookingAtBlock: 'You must be looking at a valid host block.'
