name: ${name}
main: ${groupId}.${artifactId}.Plugin
version: ${version}
description: ${description}
authors: [CoolV1994]
softdepend: [NameItem]
commands:
  enderchest:
    aliases: [ec,es,echest,endersee]
    description: Open your Ender Chest.
    usage: /<command>
    permission: portables.ENDER_CHEST.command
    permission-message: You do not have permission to use this command.
  portable:
    aliases: [p,port,open,portopen]
    description: Open the selected Portable item.
    usage: /<command>
    permission: portables.portable.command
    permission-message: You do not have permission to use this command.
  linkportable:
    aliases: [lp,pl,link]
    description: Link a Portable item with the target block.
    usage: /<command>
    permission: portables.link.command
    permission-message: You do not have permission to use this command.
  workbench:
    aliases: [wb,pwb,pct,ctable,craftingtable]
    description: Open a crafting interface.
    usage: /<command>
    permission: portables.WORKBENCH.command
    permission-message: You do not have permission to use this command.
permissions:
    portables.*:
        description: Gives all Portables permissions
        default: op
        children:
            portables.commands.*: true
            portables.use.*: true
            portables.link.*: true
            portables.customize.*: true
    portables.commands.*:
        description: Gives all Command permissions
        children:
            portables.portable.command: true
            portables.link.command: true
            portables.ENDER_CHEST.command: true
            portables.WORKBENCH.command: true
    portables.use.*:
        description: Gives all Using permissions
        children:
            portables.BREWING_STAND_ITEM.use: true
            portables.CHEST.use: true
            portables.DISPENSER.use: true
            portables.DROPPER.use: true
            portables.ENCHANTMENT_TABLE.use: true
            portables.ENDER_CHEST.use: true
            portables.FURNACE.use: true
            portables.HOPPER.use: true
            portables.WORKBENCH.use: true
    portables.link.*:
        description: Gives all Linking permissions
        children:
            portables.BREWING_STAND_ITEM.link: true
            portables.CHEST.link: true
            portables.DISPENSER.link: true
            portables.DROPPER.link: true
            portables.ENCHANTMENT_TABLE.link: true
            portables.FURNACE.link: true
            portables.HOPPER.link: true
    portables.customize.*:
        description: Gives all Customization permissions
        children:
            portables.BREWING_STAND_ITEM.customize: true
            portables.CHEST.customize: true
            portables.DISPENSER.customize: true
            portables.DROPPER.customize: true
            portables.ENCHANTMENT_TABLE.customize: true
            portables.ENDER_CHEST.customize: true
            portables.FURNACE.customize: true
            portables.HOPPER.customize: true
            portables.WORKBENCH.customize: true
    portables.BREWING_STAND_ITEM.*:
        description: Gives all Brewing Stand permissions
        children:
            portables.BREWING_STAND_ITEM.link: true
            portables.BREWING_STAND_ITEM.use: true
            portables.BREWING_STAND_ITEM.customize: true
    portables.CHEST.*:
        description: Gives all Chest permissions
        children:
            portables.CHEST.link: true
            portables.CHEST.use: true
            portables.CHEST.customize: true
    portables.DISPENSER.*:
        description: Gives all Dispenser permissions
        children:
            portables.DISPENSER.link: true
            portables.DISPENSER.use: true
            portables.DISPENSER.customize: true
    portables.DROPPER.*:
        description: Gives all Dropper permissions
        children:
            portables.DROPPER.link: true
            portables.DROPPER.use: true
            portables.DROPPER.customize: true
    portables.ENCHANTMENT_TABLE.*:
        description: Gives all Enchantment Table permissions
        children:
            portables.ENCHANTMENT_TABLE.link: true
            portables.ENCHANTMENT_TABLE.use: true
            portables.ENCHANTMENT_TABLE.customize: true
    portables.ENDER_CHEST.*:
        description: Gives all Ender Chest permissions
        children:
            portables.ENDER_CHEST.command: true
            portables.ENDER_CHEST.use: true
            portables.ENDER_CHEST.customize: true
    portables.FURNACE.*:
        description: Gives all Furnace permissions
        children:
            portables.FURNACE.link: true
            portables.FURNACE.use: true
            portables.FURNACE.customize: true
    portables.HOPPER.*:
        description: Gives all Hopper permissions
        children:
            portables.HOPPER.link: true
            portables.HOPPER.use: true
            portables.HOPPER.customize: true
    portables.WORKBENCH.*:
        description: Gives all Workbench permissions
        children:
            portables.WORKBENCH.command: true
            portables.WORKBENCH.use: true
            portables.WORKBENCH.customize: true
    portables.admin.bypasslock:
        description: Bypass Lock plugin protection
        default: op
    portables.admin.reload:
        description: Reload configuration
        default: op
