name: ${name}
main: ${groupId}.${artifactId}.Plugin
version: ${version}
description: ${description}
authors: [CoolV1994]
softdepend: [NameItem]
commands:
  enderchest:
    aliases: [ec,es,echest,endersee]
    description: Open your ender CHEST.
    usage: /<command>
    permission: portables.ENDER_CHEST.command
    permission-message: You do not have permission to use this command.
  portable:
    aliases: [p,port,open,portopen]
    description: Open the selected Portable item
    usage: /<command>
    permission: portables.portable.command
    permission-message: You do not have permission to use this command.
  linkportable:
    aliases: [lp,pl,link]
    description: Link a Portable item with the target block.
    usage: /<command>
    permission: portables.link.command
    permission-message: You do not have permission to use this command.
  workbench:
    aliases: [wb,pwb,pct,ctable,craftingtable]
    description: Open a crafting interface.
    usage: /<command>
    permission: portables.WORKBENCH.command
    permission-message: You do not have permission to use this command.
  invsee:
    aliases: [is,invview,inventorysee]
    description: Open a players inventory.
    usage: /<command> [player]
    permission: portables.invsee.command
    permission-message: You do not have permission to use this command.
permissions:
    portables.*:
        description: Gives all Portables permissions
        children:
            portables.BREWING_STAND_ITEM.*: true
            portables.CHEST.*: true
            portables.DISPENSER.*: true
            portables.DROPPER.*: true
            portables.ENCHANTMENT_TABLE.*: true
            portables.ENDER_CHEST.*: true
            portables.FURNACE.*: true
            portables.HOPPER.*: true
            portables.WORKBENCH.*: true
            portables.customize.*: true
    portables.commands:
        description: Gives all Portables permissions
        children:
            portables.ENDER_CHEST.command: true
            portables.WORKBENCH.command: true
            portables.commandlinks: true
            portables.commandopens: true
    portables.powertools:
        description: Gives all PowerTools permissions
        children:
            portables.BREWING_STAND_ITEM.powertool: true
            portables.CHEST.powertool: true
            portables.DISPENSER.powertool: true
            portables.DROPPER.powertool: true
            portables.ENCHANTMENT_TABLE.powertool: true
            portables.ENDER_CHEST.powertool: true
            portables.FURNACE.powertool: true
            portables.HOPPER.powertool: true
            portables.WORKBENCH.powertool: true
            portables.rename.powertool: true
    portables.invshortcuts:
        description: Gives all Inventory Shortcuts permissions
        children:
            portables.BREWING_STAND_ITEM.invshortcut: true
            portables.CHEST.invshortcut: true
            portables.DISPENSER.invshortcut: true
            portables.DROPPER.invshortcut: true
            portables.ENCHANTMENT_TABLE.invshortcut: true
            portables.ENDER_CHEST.invshortcut: true
            portables.FURNACE.invshortcut: true
            portables.HOPPER.invshortcut: true
            portables.WORKBENCH.invshortcut: true
    portables.links:
        description: Gives all Linking permissions
        children:
            portables.BREWING_STAND_ITEM.link: true
            portables.CHEST.link: true
            portables.DISPENSER.link: true
            portables.DROPPER.link: true
            portables.ENCHANTMENT_TABLE.link: true
            portables.FURNACE.link: true
            portables.HOPPER.link: true
    portables.commandlinks:
        description: Gives all Command Linking permissions
        children:
            portables.BREWING_STAND_ITEM.commandlink: true
            portables.CHEST.commandlink: true
            portables.DISPENSER.commandlink: true
            portables.DROPPER.commandlink: true
            portables.ENCHANTMENT_TABLE.commandlink: true
            portables.FURNACE.commandlink: true
            portables.HOPPER.commandlink: true
    portables.commandopens:
        description: Gives all Command Opening permissions
        children:
            portables.BREWING_STAND_ITEM.commandopen: true
            portables.CHEST.commandopen: true
            portables.DISPENSER.commandopen: true
            portables.DROPPER.commandopen: true
            portables.ENCHANTMENT_TABLE.commandopen: true
            portables.ENDER_CHEST.commandopen: true
            portables.FURNACE.commandopen: true
            portables.HOPPER.commandopen: true
            portables.WORKBENCH.commandopen: true
    portables.BREWING_STAND_ITEM.*:
        description: Gives all Brewing Stand permissions
        children:
            portables.BREWING_STAND_ITEM.link: true
            portables.BREWING_STAND_ITEM.invshortcut: true
            portables.BREWING_STAND_ITEM.powertool: true
            portables.BREWING_STAND_ITEM.commandlink: true
            portables.BREWING_STAND_ITEM.commandopen: true
    portables.CHEST.*:
        description: Gives all Chest permissions
        children:
            portables.CHEST.link: true
            portables.CHEST.invshortcut: true
            portables.CHEST.powertool: true
            portables.BREWING_STAND_ITEM.commandlink: true
            portables.BREWING_STAND_ITEM.commandopen: true
    portables.DISPENSER.*:
        description: Gives all Dispenser permissions
        children:
            portables.DISPENSER.link: true
            portables.DISPENSER.invshortcut: true
            portables.DISPENSER.powertool: true
            portables.DISPENSER.commandlink: true
            portables.DISPENSER.commandopen: true
    portables.DROPPER.*:
        description: Gives all Dropper permissions
        children:
            portables.DROPPER.link: true
            portables.DROPPER.invshortcut: true
            portables.DROPPER.powertool: true
            portables.DROPPER.commandlink: true
            portables.DROPPER.commandopen: true
    portables.ENCHANTMENT_TABLE.*:
        description: Gives all Enchantment Table permissions
        children:
            portables.ENCHANTMENT_TABLE.link: true
            portables.ENCHANTMENT_TABLE.invshortcut: true
            portables.ENCHANTMENT_TABLE.powertool: true
            portables.ENCHANTMENT_TABLE.commandlink: true
            portables.ENCHANTMENT_TABLE.commandopen: true
    portables.ENDER_CHEST.*:
        description: Gives all Ender Chest permissions
        children:
            portables.ENDER_CHEST.command: true
            portables.ENDER_CHEST.invshortcut: true
            portables.ENDER_CHEST.powertool: true
            portables.ENDER_CHEST.commandopen: true
    portables.FURNACE.*:
        description: Gives all Furnace permissions
        children:
            portables.FURNACE.link: true
            portables.FURNACE.invshortcut: true
            portables.FURNACE.powertool: true
            portables.FURNACE.commandlink: true
            portables.FURNACE.commandopen: true
    portables.HOPPER.*:
        description: Gives all Hopper permissions
        children:
            portables.HOPPER.link: true
            portables.HOPPER.invshortcut: true
            portables.HOPPER.powertool: true
            portables.HOPPER.commandlink: true
            portables.HOPPER.commandopen: true
    portables.WORKBENCH.*:
        description: Gives all Workbench permissions
        children:
            portables.WORKBENCH.command: true
            portables.WORKBENCH.invshortcut: true
            portables.WORKBENCH.powertool: true
            portables.WORKBENCH.commandopen: true
    portables.customize.*:
        description: Gives all Item Customization permissions
        children:
            portables.customize.BREWING_STAND_ITEM: true
            portables.customize.CHEST: true
            portables.customize.DISPENSER: true
            portables.customize.DROPPER: true
            portables.customize.ENCHANTMENT_TABLE: true
            portables.customize.ENDER_CHEST: true
            portables.customize.FURNACE: true
            portables.customize.HOPPER: true
            portables.customize.WORKBENCH: true
    portables.bypasslock:
        description: Bypass Lock plugin protection
        #default: op
    portables.invsee.command:
        description: Access to inventory see command.
    portables.modifyother:
        description: Permission to modify other players inventories.
